name: construction_website
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
#  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - "assets/images/contact registration.PNG"
    - "assets/images/license.PNG"
    - "assets/images/renewal.PNG"
    - "assets/images/shafi.jpg"
    - "assets/images/stamp.PNG"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  1.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  2.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  3.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  4.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  5.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  6.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  7.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  8.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  9.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  10.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  11.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  12.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  13.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  14.jpg"
    - "assets/images/Construction of Commishnor House at GOR-1/commissor house  15.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 1.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 2.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 3.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 4.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 5.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 6.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 7.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 8.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 9.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 10.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 11.jpg"
    - "assets/images/Construction of commercial palaza DHA 5 Islamabad/commercial palaza dha islamabad 12.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  1.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  2.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  3.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  4.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  5.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  6.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  7.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  8.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  9.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  10.jpg"
    - "assets/images/Construction of Community Hall & shops. Sec D askari 14/Community Hall  11.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 1.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 2.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 3.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 4.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 5.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 6.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 7.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 8.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 9.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 10.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 11.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 12.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 13.jpg"
    - "assets/images/Construction of Camp Office Commishnor Colony at GOR-1/camp office commishnor 14.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  1.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  2.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  3.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  4.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  5.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  6.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  7.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  8.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  9.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  10.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  11.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  12.jpg"
    - "assets/images/Karachi sand work Islamabad & Peshawar/sand work Islamabad Peshawar  13.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  1.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  2.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  3.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  4.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  5.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  6.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  7.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  8.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  9.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  10.jpg"
    - "assets/images/Stone work nathia Gali/Stone work  11.jpg"
    - "assets/images/Artificial work swat zoo/zoo 1.jpg"
    - "assets/images/Artificial work swat zoo/zoo 2.jpg"
    - "assets/images/Artificial work swat zoo/zoo 3.jpg"
    - "assets/images/Artificial work swat zoo/zoo 4.jpg"
    - "assets/images/Artificial work swat zoo/zoo 5.jpg"
    - "assets/images/Artificial work swat zoo/zoo 6.jpg"
    - "assets/images/Artificial work swat zoo/zoo 7.jpg"
    - "assets/images/Artificial work swat zoo/zoo 8.jpg"
    - "assets/images/Artificial work swat zoo/zoo 9.jpg"
    - "assets/images/Artificial work swat zoo/zoo 10.jpg"
    - "assets/images/Artificial work swat zoo/zoo 11.jpg"
    - "assets/images/Artificial work swat zoo/zoo 12.jpg"
    - "assets/images/Artificial work swat zoo/zoo 13.jpg"
    - "assets/images/Artificial work swat zoo/zoo 14.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 1.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 2.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 3.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 4.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 5.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 6.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 7.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 8.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 9.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 10.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 11.jpg"
    - "assets/images/Asphalt and PCC road Punjab regiment centr/pcc road punjab 12.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  1.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  2.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  3.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  4.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  5.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  6.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  7.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  8.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  9.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  10.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  11.jpg"
    - "assets/images/Road work commissioner colony Rawalpindi/Road work commissioner  12.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 1.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 2.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 3.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 4.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 5.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 6.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 7.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 8.jpg"
    - "assets/images/Boundary wall work Rawat/boundary wall 9.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  1.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  2.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  3.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  4.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  5.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  6.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  7.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  8.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  9.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  10.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  11.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  12.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  13.jpg"
    - "assets/images/Construction of drain work askari 13 Rawalpindi/rain work askari  14.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 1.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 2.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 3.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 4.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 5.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 6.jpg"
    - "assets/images/Construction of commercial palaza Islamabad/commercial palaza islamabad 7.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  1.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  2.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  3.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  4.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  5.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  6.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  7.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  8.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  9.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  10.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  11.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  12.jpg"
    - "assets/images/Drain work DHA 5 Islamabad/Drain work DHA  13.jpg"
